services:
  dawncaster-db:
    image: mysql:8.0
    container_name: dawncaster-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dawncaster
      MYSQL_USER: jjsh0208
      MYSQL_PASSWORD: 'Gusdk5540!'
      MYSQL_ROOT_PASSWORD: 'Gusdk5540!'
      TZ: Asia/Seoul
    volumes:
      - dawncaster_data:/var/lib/mysql

volumes:
  dawncaster_data: