services:
  dawncaster-db:
    image: mysql:8.0
    container_name: dawncaster-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - dawncaster_data:/var/lib/mysql

volumes:
  dawncaster_data: