server:
  port: 8080

spring:
  application:
    name: DawnCaster

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: ${GEMINI_MODEL}
            temperature: ${GEMINI_TEMPERATURE} # 사실 기반 요약을 위해 창의성을 낮춤


finnhub:
  api-key: ${FINNHUB_API_KEY}
  base-url: https://finnhub.io/api/v1