server:
  port: 8080

spring:
  application:
    name: DawnCaster

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: ${GEMINI_MODEL}
            temperature: ${GEMINI_TEMPERATURE} # 사실 기반 요약을 위해 창의성을 낮춤
    retry:
      max-attempts: 1 # 최대 재시도 횟수
      on-client-errors: false

  mail:
    host: smtp.gmail.com
    port: ${HOST_PORT}
    username: ${HOST_MAIL}
    password: ${HOST_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # TLS 암호화 사용 (필수)
          timeout: 5000 # 타임아웃 설정 (밀리초)


finnhub:
  api-key: ${FINNHUB_API_KEY}
  base-url: https://finnhub.io/api/v1